Building DAG of jobs...
shared_storage_local_copies: True
remote_exec: False
Using shell: /usr/bin/bash
Provided cores: 128
Rules claiming more threads will be scaled down.
Job stats:
job                    count
-------------------  -------
all                        1
bcftools_view              3
get_plot_files_rule        1
vcf_annotate               3
vcf_filter                 3
total                     11

Resources before job selection: {'_cores': 128, '_nodes': 9223372036854775807}
Ready jobs (3)
Select jobs to execute...
Selected jobs (3)
Resources after job selection: {'_cores': 125, '_nodes': 9223372036854775804}
Execute 3 jobs...

[Mon Aug 26 16:22:55 2024]
localrule bcftools_view:
    input: /n/1000g/align-card-2.24-hg38/FIRST_100/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL.phased.vcf.gz
    output: /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
    jobid: 10
    reason: Missing output files: /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
    wildcards: sample=HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg
    resources: tmpdir=/tmp


        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
        
Activating conda environment: bcftools-1.19

[Mon Aug 26 16:22:55 2024]
localrule bcftools_view:
    input: /n/1000g/align-card-2.24-hg38/FIRST_100/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz
    output: /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
    jobid: 7
    reason: Missing output files: /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
    wildcards: sample=HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC
    resources: tmpdir=/tmp


        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        
Activating conda environment: bcftools-1.19

[Mon Aug 26 16:22:55 2024]
localrule bcftools_view:
    input: /n/1000g/align-card-2.24-hg38/FIRST_100/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz
    output: /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
    jobid: 4
    reason: Missing output files: /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
    wildcards: sample=GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC
    resources: tmpdir=/tmp


        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        
Activating conda environment: bcftools-1.19
Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk", line 63, in __rule_bcftools_view
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.

Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk", line 63, in __rule_bcftools_view
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk, line 42:
Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.

RuleException:
CalledProcessError in file /n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk, line 42:
Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.
[Mon Aug 26 16:22:55 2024]
Error in rule bcftools_view:
    jobid: 10
    input: /n/1000g/align-card-2.24-hg38/FIRST_100/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL.phased.vcf.gz
    output: /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
    conda-env: bcftools-1.19
    shell:
        
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job bcftools_view since they might be corrupted:
/n/zanderson/SNP-plot-snake/parsed-VCFs/HG03861-ONT-hg38-R9-LSK110-guppy-sup-5hmc_5mc_cg.PMDV_FINAL_parsed.vcf
Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk", line 63, in __rule_bcftools_view
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.

Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk", line 63, in __rule_bcftools_view
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk, line 42:
Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.

RuleException:
CalledProcessError in file /n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk, line 42:
Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.
[Mon Aug 26 16:22:55 2024]
Error in rule bcftools_view:
    jobid: 7
    input: /n/1000g/align-card-2.24-hg38/FIRST_100/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz
    output: /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
    conda-env: bcftools-1.19
    shell:
        
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job bcftools_view since they might be corrupted:
/n/zanderson/SNP-plot-snake/parsed-VCFs/HG02409-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk", line 63, in __rule_bcftools_view
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.

Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk", line 63, in __rule_bcftools_view
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk, line 42:
Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.

RuleException:
CalledProcessError in file /n/zanderson/SNP-plot-snake/workflow/rules/bcftools-view.smk, line 42:
Command 'source /usr/bin/activate 'bcftools-1.19'; set -euo pipefail;  
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf' returned non-zero exit status 255.
[Mon Aug 26 16:22:55 2024]
Error in rule bcftools_view:
    jobid: 4
    input: /n/1000g/align-card-2.24-hg38/FIRST_100/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz
    output: /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
    conda-env: bcftools-1.19
    shell:
        
        bcftools view -R /n/zanderson/SNP-plot-snake/gene_coordinates.txt /n/1000g/align-card-2.24-hg38/FIRST_100/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL.phased.vcf.gz | bgzip > /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        bcftools index /n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job bcftools_view since they might be corrupted:
/n/zanderson/SNP-plot-snake/parsed-VCFs/GM18876-ONT-hg38-R9-LSK110-guppy-sup-5mC.PMDV_FINAL_parsed.vcf
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-08-26T162254.971999.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/workflow.py", line 1286, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
